public enum TokenType {
    // Single-character tokens
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, MINUS, PLUS, SEMICOLON, SLASH, STAR,PERCENT,CARET,

    // One or two character tokens
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    // Literals
    IDENTIFIER, STRING, NUMBER,COMMENT,

    // Keywords
    COLLECT, DONE, DOWN, DOWNLEFT, DOWNRIGHT,LEFT,RIGHT, ELSE, IF, INVEST, MOVE, NEARBY, OPPONENT,
    RELOCATE, SHOOT, THEN, UP, UPLEFT, UPRIGHT, WHILE,ATTACK,

    PLAN, // End of file
    MULTIPLY, DIVIDE, MODULO, POWER, EOF
}
